### ISSUE TITLE
Jersey client not compatible with Spring Boot 3

### ISSUE THREAD

**Issue by dominik-kovacs** [unblu/clients#1]
The jersey client doesn't work with Spring Boot 3 (Java 17) because it still uses the javax namespace. Any plans to switch to jakarta?

Got a java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration error.

**Comment by gysel** [comment]
@fbpe @jmini do we plan to address this in one of the upcoming versions?

**Comment by jmini** [comment]
As far as I know, there is no time-frame defined for this change.

We might have to provide two client versions in parallel (one with the `javax.*` package as it is now and one with the `jakarta.*` package as requested here)

**Comment by jmini** [comment]
I gave it a try on the [issue-1](https://github.com/unblu/openapi/tree/issue-1) branch.

You can use Jitpack to get a build.

**Gradle Example:**

```gradle
repositories {
    maven {
        url "https://jitpack.io"
        content {
            includeGroup "com.github.unblu.openapi"
        }
    }
    mavenCentral()
}

dependencies {
    // ...
    implementation 'com.github.unblu.openapi:jersey-client-v3:issue-1-SNAPSHOT'
    // ...
}
```

**Maven Example:**
```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>com.github.unblu.openapi</groupId>
    <artifactId>jersey-client-v3</artifactId>
    <version>issue-1-SNAPSHOT</version>
  </dependency>
  <!-- ... -->
</dependencies>
```

**JBang Example:**
This works also out of the box if you are running some script with [Jbang](https://www.jbang.dev/) by declaring the dependency like this:

```java
//DEPS https://github.com/unblu/openapi/tree/issue-1#jersey-client-v3:SNAPSHOT
```

Instead of:
```java
//DEPS com.unblu.openapi:jersey-client-v3:7.32.0
```

And then Jbang does the work of adding the additional repository for you.

**Comment by dominik-kovacs** [comment]
I've tried it on demo project for now, but looks like it works.

**Comment by jmini** [comment]
Starting with next release (end of July 2023) we will publish 2 libraries on maven central:

* `com.unblu.openapi:jersey-client-v3:<version>` as it is now based on Jersey 2
* `com.unblu.openapi:jersey3-client-v3:<version>` as it is now based on Jersey 3

In order for the consumer to have some time to adjust.

When we introduced `v4` of the Web-API (probably with Unblu 8) we will re-consider and have probably only one client based on Jersey 3.
