### ISSUE TITLE
Consider other client libraries

### ISSUE THREAD

**Issue by dominik-kovacs** [unblu/clients#4]
Please, consider also generating clients with other widely-used libraries, specifically native Java HttpClient and Spring's RestClient/RestTemplate for smoother integration.

edit: also if possible without ApiException since this is pain to handle :) or replace with unchecked exception

**Comment by jmini** [comment]
We are not sure about our strategy regarding the support of different java clients.

Ideally you could generate a client that fit your needs by using our [openapi.yaml](https://github.com/unblu/openapi/blob/HEAD/openapi.yaml) specification and a generator tool such as [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [APIMatic](https://www.apimatic.io/product/generate).

We historically started with Jersey and right now this is good enough for our use-cases. If you are an Unblu customer, please contact the support team in order for us to understand your concrete use case.
